### ISSUE TITLE
right-click on start menu no longer works

### ISSUE THREAD

**Issue by greydutch** [Open-Shell/Open-Shell-Menu#1200]
Hello,

I have been using Open-Shell for many years and I really like it. My version is current (4.4.170) and I am a Windows 11 user. Windows just updated to Version 22H2, Build 22621.674 and this is where Open Shell started to behave strangely. Whenever I right-click on the start menu the taskbar takes another colour for a split second and the icons disappear for a few moments. After that, it is back to normal. However, I cannot use the menu that is normally available when right-clicking. 

I run the setup and picked "repair", but that did not help.

Is this a known problem? Is there a fix?

Many thanks.

**Comment by ge0rdi** [comment]
Fixed in [4.4.181](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.181).

**Comment by greydutch** [comment]
I just installed version 4.4.181 but I am sorry to say that the problem still exists. I am still hoping that it will be fixed soon. Thank you.

**Comment by ge0rdi** [comment]
Do you use some other software that is changing behavior of Windows (like ExplorerPatcher)?

**Comment by greydutch** [comment]
thanks for getting back to me. no software installed that could change the behaviour of Windows (to the best of my knowledge). hope there is a solution for this issue.

**Comment by ge0rdi** [comment]
I'm sorry but I cannot replicate anything like that on clean 4.4.181+ install on clean Win11 22H2 (fully updated).

You can try to reset `Open-Shell` settings (`Open-Shell Settings` -> `Backup` -> `Reset all settings`).
But don't forget to back them up first.

**Comment by greydutch** [comment]
Thank you for your help. I made a backup of my settings and then reset the program. Then open Shell works fine. However, as soon as I use the old settings, the error occurs again. I am now enclosing the Menu Settings.xml file (saved as a pdf file, so that I can send it from here), hopig that you will find there what causes the problem. Many thanks!

[Menu Settings.pdf](https://github.com/Open-Shell/Open-Shell-Menu/files/10187922/Menu.Settings.pdf)

**Comment by ge0rdi** [comment]
You have custom start button and also custom taskbar enabled.
Try to disable those to see if that helps (and which one).

**Comment by greydutch** [comment]
I disabled both, but it does not seem to make any difference.

**Comment by ge0rdi** [comment]
Interesting.
Could you try to exit `Open-Shell` after changing the setting and then start it again?
If the result will be the same.

**Comment by greydutch** [comment]
I've done that and have found that it is indeed the start button that causes the problem! I selected this start button just to cover the standard windows button. Could you maybe recommend a start button that works properly? Many thanks for your help, it is greatly appreciated!

**Comment by ge0rdi** [comment]
> I've done that and have found that it is indeed the start button that causes the problem!

Could you provide the image you are using (`%SystemDrive%\Program Files\Open-Shell\Start 
Button\button2.png`)?
I can try to replicate the problem with that.

> Could you maybe recommend a start button that works properly?

`Aero` button that we provide by default should work correctly.
Or just disable start button customization until the problem is fixed, so that you can use start menu normally.

**Comment by greydutch** [comment]
![button2](https://user-images.githubusercontent.com/87147753/206686847-a57b7b7d-a352-4abb-a07f-ae37f3b19f65.png)

Thanks again for your help. Here's the image I have been using. Yes, I will disable button customization for the time being. Look forward to hearing from you again. Regards

**Comment by greydutch** [comment]
I have exactly the same windows update, but the "weird behaviour" is still there. However, everything is fine as long as I do not use a special start button and I can live with that. Thank you for all your help.
