### ISSUE TITLE
Taskbar texture does not fill the entire taskbar.

### ISSUE THREAD

**Issue by kwan-vini** [Open-Shell/Open-Shell-Menu#1546]
### Describe the bug

So, i was customizing the taskbar in the Open Shell settings, when i discovered this issue:
![image](https://github.com/Open-Shell/Open-Shell-Menu/assets/118130060/8aac62e4-cff7-4697-a60b-0063b7d18dc7)
The taskbar texture seems to not apply on the "tabs" part, but only on the start button and tray icons.
Could someone maybe explain or say what did i do wrong? Thanks.

### Area of issue

Taskbar

### To reproduce

Go to "Taskbar" on the Open-Shell Settings.
Click on Taskbar texture and select a image.

### Expected behavior

It's supposed to cover the enitre taskbar, right?

### Open-Shell version

4.4.170

### Windows version

Windows 10 Pro 22H2

**Comment by ge0rdi** [comment]
Please, use [latest build](https://github.com/Open-Shell/Open-Shell-Menu/releases).
It should be fixed there.

**Comment by shodanwashere** [comment]
I think this issue should be reopened because this bug is still present in the latest release.
![imagem](https://github.com/Open-Shell/Open-Shell-Menu/assets/74769749/7d54fbd6-fc9e-41bf-822c-af59ffb02ba5)

**Comment by ge0rdi** [comment]
@shodanwashere 
What is your Windows version?
Do you use also some other customization software?

**Comment by ShellUser0** [comment]
This is alao happening to me, I'm trying to make my Windows 7 Ultimate OS look like Windows 10 RTM Release.
