### ISSUE TITLE
"Show recent Metro apps" delays menu opening

### ISSUE THREAD

**Issue by Gittyperson** [Open-Shell/Open-Shell-Menu#45]
Enabling this option, causes a small (about 1 second) but noticeable delay when opening the main menu. Does not seem to occur on the Classic 1-column style (or becomes unnoticeable), confirmed on the other two styles.

http://www.classicshell.net/forum/viewtopic.php?f=7&t=4688&p=19679#p20677

**Comment by XenHat** [comment]
Known issue, mentioned elsewhere I think.

**Comment by XenHat** [comment]
Not sure what the actionable fix could be. @ge0rdi, @ibuprophen1 ?

**Comment by AveYo** [comment]
Cache them on start and only refresh them on "Highlight newly installed programs"?

**Comment by ibuprophen1** [comment]
I'm thinking that this might be tied to one of the default delays within the menu settings... 

I'd have to take a look and see. 


~Ibuprophen

**Comment by ibuprophen1** [comment]
By the way... @ge0rdi, @XenHat & @coddec is more than welcome to use the images & information from my (above) post if you want! 😨 


~Ibuprophen

**Comment by AveYo** [comment]
Dude.. that's not helpful at all. OP talks about the delay you see when using minimum values in the settings  - of course you won't feel it if you delay all the menus for 4 freaking seconds..  

The actual issue is with refreshFlags for MetroLinks but can't compile it myself atm to experiment with.

**Comment by ibuprophen1** [comment]
This issue was opened by @Gittyperson and, had not followed up with it for almost a year, it looks like this issue has been resolved or the individual found a work around (or something). 

I'm going to close this issue based upon the above... 


~Ibuprophen

**Comment by Gittyperson** [comment]
As mentioned in the title, issue is related with the Metro apps setting, and not any delay settings. Nothing has changed as far as I know (4.4.131) and the issue remains.

**Comment by ibuprophen1** [comment]
It looks, to me, like this is something that requires a Customization of a setting based upon your personal preferences. 

If I'm correct, then it's really not a software issue rather than a personal preference. 

Basically, the default settings of the software will require the individual to make changes for personalized use. This is why those options are available within the software for the individual to change them if necessary. 

Please correct me if I'm wrong.... 😱 

If, in fact, this is an issue with the actual software itself, please elaborate as I can reopen this issue. 

If an issue is found that is reflected by multiple individuals, then this would prompt the developer(s) to take another look at it for a correction. 


~Ibuprophen

**Comment by Gittyperson** [comment]
I've described it as clearly as I could on the first post. The slight delay is just the symptom. The delay settings or any other user preferences are not related.

1. Select one of these two styles: "Classic with two columns" / "Windows 7 style"
2. Open the Start Menu with the mouse button or the Win key.
3. Toggle the "Show recent Metro apps" setting on/off, and compare the speed with which the Start Menu open.

There will be a small, but noticeable additional delay when "Show recent Metro apps" is enabled.

**Comment by Gittyperson** [comment]
Confirmed again now with the default settings. I am not aware of a setting that delays the appearance of the main menu (not submenus/subfolders).

"Show recent Metro apps" is the culprit here.

**Comment by ibuprophen1** [comment]
Thank you very much for the clarification! :-) 

I'll reopen this and see if I can reproduce this myself as well. 

Maybe @coddec, @ge0rdi or @XenHat can provide some clarity with this. 


~Ibuprophen

**Comment by ibuprophen1** [comment]
@Gittyperson, I tried to duplicate this the best way I could based upon the information within this issue and I could not. 

I actually tried to duplicate it 3 times in a few different ways too... 

Is there anyone else who can help provide some additional guidance here? 


~Ibuprophen

**Comment by Gittyperson** [comment]
Ok, thanks for trying. Let's see if someone else gives it a try. Note that this delay is very subtle and it's only about opening the main menu from the start button, not subfolders or anything else.

**Comment by ibuprophen1** [comment]
@Gittyperson, are you using "Classic Shell" or "Open Shell"?

I'm asking to be sure...

Only because I've realized that issues have been submitted reflecting the older "Classic Shell" software and this GitHub Repository is for the "Open Shell" software.

Thanks a Bunch! :+1: 


~Ibuprophen

**Comment by Gittyperson** [comment]
It happens both on Classic Shell and Open Shell. Using the latter, clean install (no upgrade from CS).

**Comment by pfofi** [comment]
I can confirm **Show recent Metro apps** is the culprit here under **Main Menu** -> **Show recent or frequent programs**. The option **Frequent programs** above it also has to be enabled.

There is a noticeable delay when opening the Start Menu and CPU usage jumps for a moment.

For me, disabling that option is actually a viable workaround. Metro apps can still be found via search.

![show_recent_metro_apps](https://user-images.githubusercontent.com/7479939/62068088-a2738000-b235-11e9-9f2c-cf24164fed65.png)

**Comment by klepp0906** [comment]
Yes.  This is wreaking havoc on my experience.  If “frequent” is enabled (preliminarily doesn’t seem to affect “recent”) it hangs for about 5 seconds on my pc while it spins up my external hard disk.  

Only way around I’ve found is disabling frequent (which is my preferred like most i imagine) or shutting down my external which then makes the delay more like a second or two like the OP as opposed to much longer while it spins up a sleeping drive for who knows why :p

**Comment by klepp0906** [comment]
fwiw i opened up the start menu and the frequents list displayed 1 windowsapp.   I removed it from the list (imagine thats temporary until its re-used often enough to make it back) and the issue is gone.
so it definitely seems linked to uwd stuff appearing on that list.

still cant figure why its spinning up my external drive (or if it actually just spins up ALL drives for some reason) hence causing a big ole soft hang on my side.

**Comment by McKay42** [comment]
Can also confirm, disabling "Show recent Metro apps" decreases the delay a lot.

Previously I would start typing directly after hitting the windows key, and the keystrokes were ignored because the menu had not finished opening yet. Coming from Windows 7 muscle memory.

On the native Windows 7 start menu there was 0 delay (1 frame at most), but I'm very happy with disabling recent metro apps here (no more lost keystrokes).

With enabled "Show recent Metro apps", delay is 8 frames at 60 fps = 128 ms +-16 ms:
![delay](https://user-images.githubusercontent.com/16856443/81286495-72c59400-9061-11ea-8f28-efe7de507600.gif)

(Notice how the start button immediately updates, but the menu lags behind.)

With disabled "Show recent Metro apps", delay is 3 frames at 60 fps = 48 ms +-16 ms:
![nodelay](https://user-images.githubusercontent.com/16856443/81286705-c59f4b80-9061-11ea-8e99-c8793232a5da.gif)

**Comment by blackcrack** [comment]
could it not be possible it's due to Win10 and its response time ?
the listing of the WinNT 10 own it's *imho* also a bit womby (Wombat)

best regards
Blacky

**Comment by shicky256** [comment]
I have also been experiencing this issue. Disabling the checkbox reduces time to open the start menu from about half a second to almost instant.

**Comment by bonzibudd** [comment]
Is it possible that this can be traced down using Open-Shell's logging feature, or some other method?

I've tried to see if any other option has an effect on this, and I have found none. I tested all of the menu delay options like @Ibuprophen suggested, and I was not able to create any positive or negative effect on the initial loading time. Additionally, it seems like this issue is lesser with a faster computer, and amplified by a slower one (However, I haven't measured the time, so it could be placebo). I will try to find the version of Win10 which this issue originally appeared on, so hopefully this can help track down a change in Windows which caused this. My guess is somewhere between 2016-17.

Something that I found strange is that this issue occurs regardless of how many frequent programs are set to show. Even forcing the "All Programs" list to show automatically retains the delay. Disabling frequent programs altogether or switching to recent programs does fix it, but this isn't a solution for some people.

I will do some investigating later to see if I can track down which version caused this issue.

**Comment by ge0rdi** [comment]
> Is it possible that this can be traced down using Open-Shell's logging feature, or some other method?

You can try to create ETW trace from the issue:

- Make sure you have latest official build installed (so we can get proper symbols)
- Run `wpr -start GeneralProfile` from elevated admin console
- Replicate issue (I guess just open Start Menu)
- Run `wpr -stop trace.etl` from elevated admin console to save trace
- Upload trace somewhere and provide link to it

Note that ETW trace may contain sensitive information from your machine (it basically traces what all processes are doing).

> Additionally, it seems like this issue is lesser with a faster computer, and amplified by a slower one

On decent machine with SSD disk it is very likely you won't notice any delay (I can't see any significant delay on my machines).

**Comment by klepp0906** [comment]
fwiw i have a very fast machine on an nvme ssd.  admittedly some of the shortcuts that populate the list at times do come from items on mechanical disks however.

**Comment by ge0rdi** [comment]
> admittedly some of the shortcuts that populate the list at times do come from items on mechanical disks however.

In such case the disk may be sleeping when `Open-Shell` is accessing file on it. Thus it will have to wait till disk wakes up (which can take several seconds).

**Comment by klepp0906** [comment]
that would be a much more pronounced/protracted delay.  (plus you can hear these monsters spin up).

Its not accessing the items its simply displaying the menu which would have the shortcut icons cached i would think?  

I will say i disabled the feature quite some time ago and dealt with recent items instead/since.   I'll repay  it another visit in the near future and see if I can re-test some variables to provide a bit more info.   (all i can do as a user).

In all fairness it could have improved in the half a dozen iterations since then.

**Comment by bonzibudd** [comment]
@ge0rdi 

[trace.etl](https://1drv.ms/u/s!AqxEMH2XuF6DxHIcDfcp5gV9vSTW?e=5unFC1)

This is from newly installed virtual machine. I clicked on Start button once with the default settings, then again with recent Metro apps disabled. The delay was less than on my 2 main machines, but still significant.

**Comment by ge0rdi** [comment]
It seems the delay is caused by this [line](https://github.com/Open-Shell/Open-Shell-Menu/blob/master/Src/StartMenu/StartMenuDLL/MenuContainer.cpp#L1942) in `CMenuContainer::GetRecentPrograms`.
According to trace each call to `SHCreateItemInKnownFolder` adds ~13ms delay and there are 10 such calls.

It basically tries to resolve name of Modern app and discards records that cannot be resolved or start with `@{` (whatever that means).

Not sure if the check is really necessary. I'd try to find some replacement or basically just remove it completely.
Will create PR so you guys can check whether it will help in your cases.

**Comment by ge0rdi** [comment]
Guys, please, try build from PR #460.
It should make menu opening faster.

**Comment by bonzibudd** [comment]
@ge0rdi 

Yep, it's fast. Will be even better for mechanical drives.

**Comment by Gittyperson** [comment]
I'm not sure if there's an improvement (if there is, it's very small) but the delay is still noticeable here. (old PC, SSD on SATA 2).

**Comment by bonzibudd** [comment]
@Gittyperson 

Strange. For me, the delay is now identical w/wo recent metro apps on. It might be worth completely uninstalling and re-installing once again. I would also choose "Clear cached information" and then "Reset all settings" and see if that helps.

If none of that helps, you should make an ETL file like I did. That would help determine the issue more easily.

**Comment by Gittyperson** [comment]
I cleared everything, restarted and reinstalled. Currently on default settings. Perhaps there's a small improvement, but delay is still there. Menu opens instantly only when disabling recent Metro apps.

**Comment by bonzibudd** [comment]
Very strange. Just to make sure, is the menu settings reporting version 4.4.153?

**Comment by Gittyperson** [comment]
Yes, 4.4.153. Revisiting my first post, I had forgotten this issue does NOT occur on Classic style. I just re-confirmed this. Delay only appears on the other two styles. Perhaps that's something to investigate?

I can send the trace if necessary but I'll need an email or similar, I'd rather not post it here.

**Comment by bonzibudd** [comment]
Ok. You should get in touch with @ge0rdi . Hopefully he can provide a direct way to upload the file.

About the Classic style, this is because the default setting is to show "Recent" programs, instead of "Frequent."

**Comment by ge0rdi** [comment]
@Gittyperson 
Its a shame that Github doesn't have a way to share sensitive content with project members :(

Feel free to upload ETL to some cloud storage and send me a link to `ge0rdi (at) gmx.com` .
I'll try to have a look.

**Comment by XenHat** [comment]
if it's really sensitive, you can use gnupg. keybase.io provides a decent interface

**Comment by ge0rdi** [comment]
@XenHat 
Thanks for the tip.

I just meant that it will be great if there will be some way how users could share such information with project members on Github without exposing their private e-mails/keybase.io id/etc.
This would be great for providing crash-dumps, ETW logs and other kind of debug information.

**Comment by Gittyperson** [comment]
Ok, just sent it. Includes both 4.4.152/3 trace files, not sure which one you preferred. Same as bonzibudd: clicked on Start button once with the default settings, then again with recent Metro apps disabled.

**Comment by ge0rdi** [comment]
@Gittyperson 
You have used build from different PR.

Please, use build from PR #460.
Here is direct link to [installer](https://ci.appveyor.com/api/buildjobs/deg7jiq61o34tcrk/artifacts/OpenShellSetup_4_4_153-rcwdhlxn.exe).

Note that these builds from pull-requests are _unofficial_, so they are not meant for daily usage. Just for checking whether given fix/change works as expected.

Once PR will be merged to master, there will be _official_ build created that can be downloaded via [Latest nightly build](https://ci.appveyor.com/project/passionate-coder/open-shell-menu/branch/master/artifacts) link.

**Comment by Gittyperson** [comment]
Thanks, took me a while to locate an installer there... and I got the wrong one.

With a quick test, I'd say there's a 90% improvement. 👍 A barely perceptible delay still remains, but on newer PCs it probably won't be there at all. Many thanks, ge0rdi!

**Comment by ge0rdi** [comment]
Change is now merged to master.
Please, use latest nightly build (4.4.154) that contains it.
